[build]
  CI= "npm run build"
  publish = "dist"
  NODE_ENV = "20.11.1"


[dev]
  CI= "npm run build"


[build.processing.html]
  pretty_urls = true


[[redirects]]
  # Requests to URLs matching this pattern...
  from = "/assets/img/*"
  # ...will resolve to this URL pattern
  to = "/.netlify/images?url=/assets/img/*"
  # ... and the status code of 200 will make this behave as a rewrite
  status = 200


[[redirects]]
  # ...or serve a resized version
  from = "/assets/img/480/*"
  to = "/.netlify/images?url=/assets/img/*&width=480"
  status = 200

[[redirects]]
  # ...or serve a resized version
  from = "/assets/img/768/*"
  to = "/.netlify/images?url=/assets/img/*&width=768"
  status = 200

[[redirects]]
  # ...or serve a resized version
  from = "/assets/img/1024/*"
  to = "/.netlify/images?url=/assets/img/*&width=1024"
  status = 200

[[redirects]]
  # ...or serve a resized version
  from = "/assets/img/1920/*"
  to = "/.netlify/images?url=/assets/img/*&width=1920"
  status = 200