backend:
  name: github
  repo: thegrandheavybold/atelierwehrle__com
  branch: main
  
publish_mode: editorial_workflow

local_backend: true

media_folder: "/src/assets/img"
public_folder: "/assets/img"

i18n:
  structure: multiple_folders
  locales: [de, en]
  default_locale: de 

collections:
  - label: "Gärten"
    name: "gaerten"
    folder: "src/gaerten"
    slug: "{{slug}}"   # ✅ use filename as fallback slug
    path: "{{slug}}"   # URL remains based on slug
    create: true
    i18n: true
    extension: "md"
    format: "frontmatter"
    fields:

      - { label: "Title", name: "title", widget: "string", i18n: true }

      - label: "Datum"
        name: "date"
        widget: "datetime"
        format: "YYYY-MM-DDTHH:mm"
        picker_utc: false
        required: true
        default: ""
        i18n: true

      - label: "URL Slug"
        name: "urlSlug"
        widget: "string"
        hint: "URL-Bezeichnung"
        required: true
        i18n: true
      
      - label: "SEO Meta Tags"
        name: "metaTags"
        widget: "object"
        i18n: true
        fields:
          - { label: "Meta Title", name: "metatitle", widget: "string", i18n: true, required: false }
          - { label: "Meta Description", name: "metaDescription", widget: "text", i18n: true, required: false }

      - label: "Featured"
        name: "featured"
        widget: "object"
        i18n: true  
        fields:
          - { label: "Featured Image", name: "featImage", widget: "image", i18n: true, choose_url: false, required: false, media_folder: "/src/assets/img", public_folder: "/assets/img" }
          - { label: "Alt Text", name: "alt", widget: "string", i18n: true }


      - label: "Main Article"
        name: "mainArticle"
        widget: "object"
        i18n: true
        required: false
        fields:
          - label: "Article Header"
            name: "articleHeader"
            widget: "object"
            required: false
            i18n: true
            fields:
              - { label: "Opener Image", name: "openerImage", widget: "image", i18n: true, choose_url: false, required: false, media_folder: "/src/assets/img", public_folder: "/assets/img" }
              - { label: "Alt Text", name: "alt", widget: "string", i18n: true, required: false }

          - label: "Gallery"
            name: "galleryImages"
            widget: "list"
            i18n: true
            required: false
            fields:
              - { label: "Image", name: "image", widget: "image", i18n: true, choose_url: false, required: false, media_folder: "/src/assets/img", public_folder: "/assets/img" }
              - { label: "Alt Text", name: "alt", widget: "string", required: false }

          - { label: "Article Copy", name: "copy", widget: "text", i18n: true, required: false }

          - label: "Article Footer"
            name: "articleFooter"
            widget: "object"
            i18n: true
            required: false
            fields:
              - { label: "Closing Image", name: "closingImage", widget: "image", i18n: true, choose_url: false, required: false, media_folder: "/src/assets/img", public_folder: "/assets/img" }
              - { label: "Alt Text", name: "alt", widget: "string", i18n: true, required: false }

          - label: "Article Credits"
            name: "articleCredits"
            widget: "object"
            i18n: true
            fields:
              - { label: "Entwurf & Ausführungsplanung", name: "entwurf", widget: "string", i18n: true, required: false }
              - { label: "Ausführung", name: "ausfuehrung", widget: "string", i18n: true, required: false }
              - { label: "Bilder", name: "bilder", widget: "string", i18n: true, required: false }